# 에러 처리

## 원인 분석을 위한 에러처리
  - 완성도 있는 소프트웨어 개발을 위해 예상 가능한 모든 에러 상황을 고려하여 적절한 처리 로직을 작성해야 한다.
  - 대표적으로 자바의 try-catch 구문이 있다. try 구문에 에러가 나올 가능성이 있는 코드를 작성하고, 실행 과정에서 에러가 나오면 catch 구문에서 예외 처리를 한다.
  - finally는 어떤 상황에서든 무조건 수행되어야 하는 코드 영역이다. 예외가 발생하여 catch 구문이 실행되어도 finally는 동작한다.
  - 자원 낭비를 위해 자원을 해제해주는 작업 등이 finally에 포함된다.
    ```java
    public class MyClass extends MyCustomException {
      public static void main(String[] args) {
      
        try {
          /*
          예외가 발생할 수 있는 프로그램 코드 영역
          */
        } catch (MyCustomException e) {
            /*
            예외 발생 시 처리할 코드 영역
            */
        } finally {
            /*
            예외 발생 상황과는 관계 없이 무조건 수행되는 코드 영역
            */
        }
      }
    
    }
    ```

## 예외 처리 코드가 부재할 경우
  - 예외가 발생했을 때의 적절한 처리 로직을 구현하지 않으면, 프로그램이 중지되며 사용자 친화적 결과가 제공되지 않고 IDE 등이 제공하는 기계적 메시지가 클라이언트에 노출된다.
  - catch 구문에 시스템 로그라도 찍어서 어떤 문제가 있는지 확인할 수 있는 최소한의 조치가 있어야 한다.

## 예외를 던진다(throw), 예외를 받는다.(catch)
  - throw: 예외사항이 발생하면 이 메서드를 호출한 코드에 Exception을 던진다. 던져서 처리하라고 권한을 넘긴다.
  - catch: 어디선가 던져진 Exception을 갈고리로 잡아 와서 처리할 처리할 준비를 한다.







